import React, { createContext, useReducer } from 'react';
import AppReducer from './AppReducer';

// Initial State
const initialState = {
  countries: [
    { value: 'AF', label: 'Afeganistão' },
    { value: 'ZA', label: 'África do Sul' },
    { value: 'AX', label: 'Åland, Ilhas' },
    { value: 'AL', label: 'Albânia' },
    { value: 'DE', label: 'Alemanha' },
    { value: 'AD', label: 'Andorra' },
    { value: 'AO', label: 'Angola' },
    { value: 'AI', label: 'Anguilla' },
    { value: 'AQ', label: 'Antárctida' },
    { value: 'AG', label: 'Antígua e Barbuda' },
    { value: 'SA', label: 'Arábia Saudita' },
    { value: 'DZ', label: 'Argélia' },
    { value: 'AR', label: 'Argentina' },
    { value: 'AM', label: 'Armênia' },
    { value: 'AW', label: 'Aruba' },
    { value: 'AU', label: 'Austrália' },
    { value: 'AT', label: 'Áustria' },
    { value: 'AZ', label: 'Azerbaijão' },
    { value: 'BS', label: 'Bahamas' },
    { value: 'BH', label: 'Bahrain' },
    { value: 'BD', label: 'Bangladesh' },
    { value: 'BB', label: 'Barbados' },
    { value: 'BE', label: 'Bélgica' },
    { value: 'BZ', label: 'Belize' },
    { value: 'BJ', label: 'Benim' },
    { value: 'BM', label: 'Bermudas' },
    { value: 'BY', label: 'Bielorrússia' },
    { value: 'BO', label: 'Bolívia' },
    { value: 'BQ', label: 'Bonaire, Santo Eustáquio e Saba' },
    { value: 'BA', label: 'Bósnia e Herzegovina' },
    { value: 'BW', label: 'Botswana' },
    { value: 'BV', label: 'Bouvet, Ilha' },
    { value: 'BR', label: 'Brasil' },
    { value: 'BN', label: 'Brunei' },
    { value: 'BG', label: 'Bulgária' },
    { value: 'BF', label: 'Burkina Faso' },
    { value: 'BI', label: 'Burundi' },
    { value: 'BT', label: 'Butão' },
    { value: 'CV', label: 'Cabo Verde' },
    { value: 'CM', label: 'Camarões' },
    { value: 'KH', label: 'Cambodja' },
    { value: 'CA', label: 'Canadá' },
    { value: 'KY', label: 'Cayman, Ilhas' },
    { value: 'KZ', label: 'Cazaquistão' },
    { value: 'CF', label: 'Centro-Africana, República' },
    { value: 'TD', label: 'Chade' },
    { value: 'CZ', label: 'Checa, República' },
    { value: 'CL', label: 'Chile' },
    { value: 'CN', label: 'China' },
    { value: 'CY', label: 'Chipre' },
    { value: 'CX', label: 'Christmas, Ilha' },
    { value: 'CC', label: 'Cocos, Ilhas' },
    { value: 'CO', label: 'Colômbia' },
    { value: 'KM', label: 'Comores' },
    { value: 'CD', label: 'Congo, República Democrática do (antigo Zaire)' },
    { value: 'CG', label: 'Congo, República do' },
    { value: 'CK', label: 'Cook, Ilhas' },
    { value: 'KR', label: 'Coréia do Sul' },
    { value: 'KP', label: 'Coréia do Norte' },
    { value: 'CI', label: 'Costa do Marfim' },
    { value: 'CR', label: 'Costa Rica' },
    { value: 'HR', label: 'Croácia' },
    { value: 'CU', label: 'Cuba' },
    { value: 'CW', label: 'Curacao' },
    { value: 'DK', label: 'Dinamarca' },
    { value: 'DJ', label: 'Djibouti' },
    { value: 'DM', label: 'Dominica' },
    { value: 'DO', label: 'Dominicana, República' },
    { value: 'EG', label: 'Egito' },
    { value: 'SV', label: 'El Salvador' },
    { value: 'AE', label: 'Emirados Árabes Unidos' },
    { value: 'EC', label: 'Equador' },
    { value: 'ER', label: 'Eritreia' },
    { value: 'SK', label: 'Eslováquia' },
    { value: 'SI', label: 'Eslovênia' },
    { value: 'ES', label: 'Espanha' },
    { value: 'US', label: 'Estados Unidos' },
    { value: 'EE', label: 'Estónia' },
    { value: 'ET', label: 'Etiópia' },
    { value: 'FO', label: 'Feroé, Ilhas' },
    { value: 'FJ', label: 'Fiji' },
    { value: 'PH', label: 'Filipinas' },
    { value: 'FI', label: 'Finlândia' },
    { value: 'FR', label: 'França' },
    { value: 'GA', label: 'Gabão' },
    { value: 'GM', label: 'Gâmbia' },
    { value: 'GH', label: 'Gana' },
    { value: 'GE', label: 'Geórgia' },
    { value: 'GS', label: 'Geórgia do Sul e Sandwich do Sul, Ilhas' },
    { value: 'GI', label: 'Gibraltar' },
    { value: 'GR', label: 'Grécia' },
    { value: 'GD', label: 'Grenada' },
    { value: 'GL', label: 'Groenlândia' },
    { value: 'GP', label: 'Guadalupe' },
    { value: 'GU', label: 'Guam' },
    { value: 'GT', label: 'Guatemala' },
    { value: 'GG', label: 'Guernsey' },
    { value: 'GY', label: 'Guiana' },
    { value: 'GF', label: 'Guiana Francesa' },
    { value: 'GQ', label: 'Guiné Equatorial' },
    { value: 'GW', label: 'Guiné-Bissau' },
    { value: 'GN', label: 'Guiné-Conacri' },
    { value: 'HT', label: 'Haiti' },
    { value: 'HN', label: 'Honduras' },
    { value: 'HK', label: 'Hong Kong' },
    { value: 'HU', label: 'Hungria' },
    { value: 'YE', label: 'Iémen' },
    { value: 'HM', label: 'Ilha Heard e Ilhas McDonald' },
    { value: 'IN', label: 'Índia' },
    { value: 'ID', label: 'Indonésia' },
    { value: 'IR', label: 'Irã' },
    { value: 'IQ', label: 'Iraque' },
    { value: 'IE', label: 'Irlanda' },
    { value: 'IS', label: 'Islândia' },
    { value: 'IL', label: 'Israel' },
    { value: 'IT', label: 'Itália' },
    { value: 'JM', label: 'Jamaica' },
    { value: 'JP', label: 'Japão' },
    { value: 'JE', label: 'Jersey' },
    { value: 'JO', label: 'Jordânia' },
    { value: 'KI', label: 'Kiribati' },
    { value: 'XK', label: 'Kosovo' },
    { value: 'KW', label: 'Kuwait' },
    { value: 'LA', label: 'Laos' },
    { value: 'LS', label: 'Lesoto' },
    { value: 'LV', label: 'Letônia' },
    { value: 'LB', label: 'Líbano' },
    { value: 'LR', label: 'Libéria' },
    { value: 'LY', label: 'Líbia' },
    { value: 'LI', label: 'Liechtenstein' },
    { value: 'LT', label: 'Lituânia' },
    { value: 'LU', label: 'Luxemburgo' },
    { value: 'MO', label: 'Macau' },
    { value: 'MK', label: 'Macedônia, República da' },
    { value: 'MG', label: 'Madagáscar' },
    { value: 'MY', label: 'Malásia' },
    { value: 'MW', label: 'Malawi' },
    { value: 'MV', label: 'Maldivas' },
    { value: 'ML', label: 'Mali' },
    { value: 'MT', label: 'Malta' },
    { value: 'FK', label: 'Malvinas, Ilhas (Falkland)' },
    { value: 'IM', label: 'Man, Ilha de' },
    { value: 'MP', label: 'Marianas Setentrionais' },
    { value: 'MA', label: 'Marrocos' },
    { value: 'MH', label: 'Marshall, Ilhas' },
    { value: 'MQ', label: 'Martinica' },
    { value: 'MU', label: 'Maurícia' },
    { value: 'MR', label: 'Mauritânia' },
    { value: 'YT', label: 'Mayotte' },
    { value: 'UM', label: 'Menores Distantes dos Estados Unidos, Ilhas' },
    { value: 'MX', label: 'México' },
    { value: 'FM', label: 'Micronésia, Estados Federados da' },
    { value: 'MZ', label: 'Moçambique' },
    { value: 'MD', label: 'Moldávia' },
    { value: 'MC', label: 'Mônaco' },
    { value: 'MN', label: 'Mongólia' },
    { value: 'ME', label: 'Montenegro' },
    { value: 'MS', label: 'Montserrat' },
    { value: 'MM', label: 'Myanmar (antiga Birmânia)' },
    { value: 'NA', label: 'Namíbia' },
    { value: 'NR', label: 'Nauru' },
    { value: 'NP', label: 'Nepal' },
    { value: 'NI', label: 'Nicarágua' },
    { value: 'NE', label: 'Níger' },
    { value: 'NG', label: 'Nigéria' },
    { value: 'NU', label: 'Niue' },
    { value: 'NF', label: 'Norfolk, Ilha' },
    { value: 'NO', label: 'Noruega' },
    { value: 'NC', label: 'Nova Caledônia' },
    { value: 'NZ', label: 'Nova Zelândia (Aotearoa)' },
    { value: 'OM', label: 'Oman' },
    { value: 'NL', label: 'Países Baixos (Holanda)' },
    { value: 'PW', label: 'Palau' },
    { value: 'PS', label: 'Palestina' },
    { value: 'PA', label: 'Panamá' },
    { value: 'PG', label: 'Papua-Nova Guiné' },
    { value: 'PK', label: 'Paquistão' },
    { value: 'PY', label: 'Paraguai' },
    { value: 'PE', label: 'Peru' },
    { value: 'PN', label: 'Pitcairn' },
    { value: 'PF', label: 'Polinésia Francesa' },
    { value: 'PL', label: 'Polônia' },
    { value: 'PR', label: 'Porto Rico' },
    { value: 'PT', label: 'Portugal' },
    { value: 'QA', label: 'Qatar' },
    { value: 'KE', label: 'Quênia' },
    { value: 'KG', label: 'Quirguistão' },
    { value: 'GB', label: 'Reino Unido da Grã-Bretanha e Irlanda do Norte' },
    { value: 'RE', label: 'Reunião' },
    { value: 'RO', label: 'Romênia' },
    { value: 'RW', label: 'Ruanda' },
    { value: 'RU', label: 'Rússia' },
    { value: 'EH', label: 'Saara Ocidental' },
    { value: 'MF', label: 'Saint Martin' },
    { value: 'PM', label: 'Saint Pierre et Miquelon' },
    { value: 'SB', label: 'Salomão, Ilhas' },
    { value: 'WS', label: 'Samoa (Samoa Ocidental)' },
    { value: 'AS', label: 'Samoa Americana' },
    { value: 'SM', label: 'San Marino' },
    { value: 'SH', label: 'Santa Helena' },
    { value: 'LC', label: 'Santa Lúcia' },
    { value: 'BL', label: 'São Bartolomeu' },
    { value: 'KN', label: 'São Cristóvão e Névis (Saint Kitts e Nevis)' },
    { value: 'ST', label: 'São Tomé e Príncipe' },
    { value: 'VC', label: 'São Vicente e Granadinas' },
    { value: 'SN', label: 'Senegal' },
    { value: 'SL', label: 'Serra Leoa' },
    { value: 'RS', label: 'Sérvia' },
    { value: 'SC', label: 'Seychelles' },
    { value: 'SG', label: 'Singapura' },
    { value: 'SX', label: 'Sint Maarten' },
    { value: 'SY', label: 'Síria' },
    { value: 'SO', label: 'Somália' },
    { value: 'LK', label: 'Sri Lanka' },
    { value: 'SZ', label: 'Suazilândia' },
    { value: 'SD', label: 'Sudão' },
    { value: 'SS', label: 'Sudão do Sul' },
    { value: 'SE', label: 'Suécia' },
    { value: 'CH', label: 'Suíça' },
    { value: 'SR', label: 'Suriname' },
    { value: 'SJ', label: 'Svalbard e Jan Mayen' },
    { value: 'TH', label: 'Tailândia' },
    { value: 'TW', label: 'Taiwan' },
    { value: 'TJ', label: 'Tajiquistão' },
    { value: 'TZ', label: 'Tanzânia' },
    { value: 'TF', label: 'Terras Austrais e Antárticas Francesas (TAAF)' },
    { value: 'IO', label: 'Território Britânico do Oceano Índico' },
    { value: 'TL', label: 'Timor-Leste' },
    { value: 'TG', label: 'Togo' },
    { value: 'TO', label: 'Tonga' },
    { value: 'TK', label: 'Toquelau' },
    { value: 'TT', label: 'Trindade e Tobago' },
    { value: 'TN', label: 'Tunísia' },
    { value: 'TC', label: 'Turks e Caicos' },
    { value: 'TM', label: 'Turquemenistão' },
    { value: 'TR', label: 'Turquia' },
    { value: 'TV', label: 'Tuvalu' },
    { value: 'UA', label: 'Ucrânia' },
    { value: 'UG', label: 'Uganda' },
    { value: 'UY', label: 'Uruguai' },
    { value: 'UZ', label: 'Usbequistão' },
    { value: 'VU', label: 'Vanuatu' },
    { value: 'VA', label: 'Vaticano' },
    { value: 'VE', label: 'Venezuela' },
    { value: 'VN', label: 'Vietnam' },
    { value: 'VI', label: 'Virgens Americanas, Ilhas' },
    { value: 'VG', label: 'Virgens Britânicas, Ilhas' },
    { value: 'WF', label: 'Wallis e Futuna' },
    { value: 'ZM', label: 'Zâmbia' },
    { value: 'ZW', label: 'Zimbabwe' },
  ],
  country: { value: 'BR', label: 'Brasil' },
};

// Create the Context
export const GlobalContext = createContext(initialState);

export const GlobalProvider = ({ children }) => {
  const [state, dispatch] = useReducer(AppReducer, initialState, undefined);

  const handleCountryChange = isoCode => {
    dispatch({
      type: 'HANDLE_COUNTRY_CHANGE',
      payload: isoCode,
    });
  };

  return (
    <GlobalContext.Provider value={{...state, handleCountryChange }}>
      {children}
    </GlobalContext.Provider>
  );
};
